"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'uz' | 'ru' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations = {
  uz: {
    // Navigation
    'nav.dashboard': 'Boshqaruv paneli',
    'nav.attendance': 'Davomat',
    'nav.homework': 'Uy vazifasi',
    'nav.gradebook': 'Baholar kitobi',
    'nav.profile': 'Profil',
    'nav.settings': 'Sozlamalar',
    'nav.logout': 'Chiqish',
    'nav.search': 'Qidirish...',
    
    // Teacher specific
    'teacher.myStudents': 'Mening o\'quvchilarim',
    'teacher.myClasses': 'Mening sinflarim',
    'teacher.exams': 'Imtihonlar',
    'teacher.announcements': 'E\'lonlar',
    
    // Student specific
    'student.myGrades': 'Mening baholarim',
    'student.exams': 'Imtihonlar',
    'student.results': 'Natijalar',
    'student.announcements': 'E\'lonlar',
    
    // Common
    'common.homework': 'Uy vazifasi',
    'common.attendance': 'Davomat',
    'common.grades': 'Baholar',
    'common.submit': 'Yuborish',
    'common.cancel': 'Bekor qilish',
    'common.save': 'Saqlash',
    'common.edit': 'Tahrirlash',
    'common.delete': 'O\'chirish',
    'common.view': 'Ko\'rish',
    'common.download': 'Yuklab olish',
    'common.upload': 'Yuklash',
    'common.filter': 'Filtr',
    'common.search': 'Qidirish',
    'common.loading': 'Yuklanmoqda...',
    'common.error': 'Xatolik',
    'common.success': 'Muvaffaqiyat',
    'common.warning': 'Ogohlantirish',
    'common.info': 'Ma\'lumot',
    'common.backToList': 'Ro\'yxatga qaytish',
    
    // Homework
    'homework.title': 'Uy vazifasi',
    'homework.dueDate': 'Topshirish muddati',
    'homework.subject': 'Fan',
    'homework.description': 'Tavsif',
    'homework.status': 'Holat',
    'homework.submitted': 'Topshirilgan',
    'homework.pending': 'Kutilmoqda',
    'homework.graded': 'Baholangan',
    'homework.overdue': 'Muddati o\'tgan',
    'homework.submit': 'Topshirish',
    'homework.update': 'Yangilash',
    'homework.view': 'Ko\'rish',
    'homework.grade': 'Baho',
    'homework.feedback': 'Fikr-mulohaza',
    'homework.attachments': 'Ilovalar',
    'homework.textContent': 'Matn mazmuni',
    'homework.voiceRecording': 'Ovozli yozuv',
    'homework.uploadFile': 'Fayl yuklash',
    'homework.recordVoice': 'Ovoz yozish',
    'homework.removeContent': 'Mazmunni o\'chirish',
    'homework.removeAttachment': 'Ilovani o\'chirish',
    'homework.submissionDetails': 'Topshirish tafsilotlari',
    'homework.teacherFeedback': 'O\'qituvchi fikri',
    'homework.submittedAt': 'Topshirilgan vaqt',
    'homework.gradedAt': 'Baholangan vaqt',
    'homework.selectHomework': 'Uy vazifasini tanlang',
    'homework.selectHomeworkDesc': 'O\'quvchi topshiriqlarini ko\'rish va baholash uchun uy vazifasini tanlang.',
    'homework.loadingSubmissions': 'Topshiriqlar yuklanmoqda...',
    'homework.notFound': 'Uy vazifasi topilmadi',
    'homework.notFoundDesc': 'Tanlangan uy vazifasi topilmadi.',
    'homework.submission': 'topshiriq',
    'homework.lateSubmission': 'Kech topshiriq',
    'homework.pendingReview': 'Ko\'rib chiqilmoqda',
    'homework.studentId': 'O\'quvchi ID',
    'homework.submissionText': 'Topshiriq matni',
    'homework.submissionInfo': 'Topshiriq ma\'lumoti',
    'homework.notSubmitted': 'Topshirilmagan',
    'homework.time': 'Vaqt',
    'homework.onTime': 'O\'z vaqtida',
    'homework.audioNotSupported': 'Brauzeringiz audio elementini qo\'llab-quvvatlamaydi.',
    'homework.noAttachments': 'Qo\'shimchalar yo\'q',
    'homework.gradeSubmission': 'Topshiriqni baholash',
    'homework.gradeOutOf': 'Baho (maksimal',
    'homework.enterGrade': 'Bahoni kiriting',
    'homework.enterFeedback': 'O\'quvchi uchun fikr-mulohaza kiriting...',
    'homework.saving': 'Saqlanmoqda...',
    'homework.saveGradeFeedback': 'Baho va fikrni saqlash',
    'homework.noSubmissions': 'Hali topshiriqlar yo\'q',
    'homework.noSubmissionsDesc': 'O\'quvchilar hali uy vazifalarini topshirmaganlar.',
    
    // Attendance
    'attendance.title': 'Davomat',
    'attendance.takeAttendance': 'Davomat olish',
    'attendance.markAllPresent': 'Barchasini hozir deb belgilash',
    'attendance.markAllAbsent': 'Barchasini yo\'q deb belgilash',
    'attendance.markAllLate': 'Barchasini kech kelgan deb belgilash',
    'attendance.markAllExcused': 'Barchasini uzrli deb belgilash',
    'attendance.quickActions': 'Tez amallar',
    'attendance.present': 'Hozir',
    'attendance.absent': 'Yo\'q',
    'attendance.late': 'Kech kelgan',
    'attendance.excused': 'Uzrli',
    'attendance.analytics': 'Tahlil',
    'attendance.tracker': '30 kunlik kuzatuv',
    'attendance.statistics': 'Statistika',
    'attendance.percentage': 'Foiz',
    'attendance.period': 'Davr',
    'attendance.last7days': 'So\'nggi 7 kun',
    'attendance.last4weeks': 'So\'nggi 4 hafta',
    'attendance.last12weeks': 'So\'nggi 12 hafta',
    'attendance.thisYear': 'Bu yil',
    'attendance.filter': 'Filtr',
    'attendance.allSubjects': 'Barcha fanlar',
    'attendance.month': 'Oy',
    'attendance.previousMonth': 'Oldingi oy',
    'attendance.nextMonth': 'Keyingi oy',
    'attendance.addNotes': 'Izoh qo\'shish (ixtiyoriy)',
    'attendance.saved': 'Davomat muvaffaqiyatli saqlandi!',
    'attendance.failedToSave': 'Davomatni saqlashda xatolik yuz berdi',
    
    // Teacher Panel - Schedule Dashboard
    'teacher.schedule.title': 'Dars jadvali',
    'teacher.schedule.lesson': 'Dars',
    'teacher.schedule.room': 'Xona',
    'teacher.schedule.class': 'Sinf',
    'teacher.schedule.subject': 'Fan',
    'teacher.schedule.time': 'Vaqt',
    'teacher.schedule.topic': 'Mavzu',
    'teacher.schedule.takeAttendance': 'Davomat olish',
    'teacher.schedule.inputGrades': 'Baho kiritish',
    'teacher.schedule.assignHomework': 'Uy vazifasi berish',
    'teacher.schedule.editTopic': 'Mavzuni tahrirlash',
    'teacher.schedule.upcoming': 'Kutilayotgan',
    'teacher.schedule.inProgress': 'Davom etayotgan',
    'teacher.schedule.completed': 'Tugagan',
    'teacher.schedule.noLessons': 'Bugun darslar yo\'q',
    'teacher.schedule.enjoyFreeTime': 'Bo\'sh vaqtingizdan zavqlaning!',
    'teacher.schedule.quickActions': 'Tez harakatlar',
    'teacher.schedule.markAllPresent': 'Hammasini hozir deb belgilash',
    'teacher.schedule.markAllAbsent': 'Hammasini yo\'q deb belgilash',
    'teacher.schedule.markAllLate': 'Hammasini kech kelgan deb belgilash',
    'teacher.schedule.markAllExcused': 'Hammasini uzrli deb belgilash',
    'teacher.schedule.addNotes': 'Izoh qo\'shish (ixtiyoriy)',
    'teacher.schedule.saveAttendance': 'Davomatni saqlash',
    'teacher.schedule.attendanceSaved': 'Davomat muvaffaqiyatli saqlandi!',
    'teacher.schedule.failedToSave': 'Davomatni saqlashda xatolik yuz berdi',
    'teacher.schedule.subjectTeacher': 'Fan o\'qituvchisi',
    'teacher.schedule.supervisor': 'Nazoratchi',
    'teacher.schedule.noLessonTopic': 'Dars mavzusi yo\'q',
    'teacher.schedule.loading': 'Yuklanmoqda...',
    'teacher.schedule.attendanceUpcoming': 'Dars boshlanganda davomat olish mumkin',
    'teacher.schedule.attendanceCompleted': 'Dars tugagan - davomat yopilgan',
    'teacher.schedule.attendanceAvailable': 'Davomat olish',
    'teacher.schedule.status.upcoming': 'Kutilayotgan',
    'teacher.schedule.status.inProgress': 'Davom etayotgan',
    'teacher.schedule.status.completed': 'Tugagan',

    // Teacher Panel - Grades
    'teacher.grades.title': 'Baholar',
    'teacher.grades.inputGrades': 'Baho kiritish',
    'teacher.grades.gradeTracker': 'Baho kuzatuvchisi',
    'teacher.grades.analytics': 'Tahlil',
    'teacher.grades.assignmentTitle': 'Topshiriq nomi',
    'teacher.grades.maxScore': 'Maksimal baho',
    'teacher.grades.gradeType': 'Baho turi',
    'teacher.grades.dailyGrade': 'Kunlik baho',
    'teacher.grades.homework': 'Uy vazifasi',
    'teacher.grades.quiz': 'Test',
    'teacher.grades.test': 'Imtihon',
    'teacher.grades.project': 'Loyiha',
    'teacher.grades.participation': 'Faollik',
    'teacher.grades.excellent': 'A\'lo (90-100%)',
    'teacher.grades.good': 'Yaxshi (80-89%)',
    'teacher.grades.satisfactory': 'Qoniqarli (70-79%)',
    'teacher.grades.needsImprovement': 'Yaxshilanish kerak (0-69%)',
    'teacher.grades.outOf': 'dan',
    'teacher.grades.feedback': 'Fikr-mulohaza',
    'teacher.grades.saveGrades': 'Baholarni saqlash',
    'teacher.grades.gradesSaved': 'Baholar muvaffaqiyatli saqlandi!',
    'teacher.grades.failedToSave': 'Baholarni saqlashda xatolik yuz berdi',
    'teacher.grades.student': 'O\'quvchi',
    'teacher.grades.score': 'Baho',
    'teacher.grades.grade': 'Baho',
    'teacher.grades.percentage': 'Foiz',
    'teacher.grades.letterGrade': 'Harf bahosi',
    'teacher.grades.date': 'Sana',
    'teacher.grades.type': 'Turi',

    // Teacher Panel - Homework
    'teacher.homework.title': 'Uy vazifasi',
    'teacher.homework.create': 'Uy vazifasi yaratish',
    'teacher.homework.assign': 'Uy vazifasini belgilash',
    'teacher.homework.titleField': 'Sarlavha',
    'teacher.homework.description': 'Tavsif',
    'teacher.homework.instructions': 'Ko\'rsatmalar',
    'teacher.homework.dueDate': 'Topshirish muddati',
    'teacher.homework.totalPoints': 'Umumiy ball',
    'teacher.homework.passingPoints': 'O\'tish ballari',
    'teacher.homework.allowLate': 'Kech topshirishga ruxsat berish',
    'teacher.homework.latePenalty': 'Kech topshirish uchun jarima',
    'teacher.homework.attachments': 'Ilovalar',
    'teacher.homework.uploadFiles': 'Fayllarni yuklash',
    'teacher.homework.fileSelected': 'fayl tanlandi',
    'teacher.homework.filesSelected': 'fayl tanlandi',
    'teacher.homework.removeFile': 'Faylni olib tashlash',
    'teacher.homework.createHomework': 'Uy vazifasini yaratish',
    'teacher.homework.homeworkCreated': 'Uy vazifasi muvaffaqiyatli yaratildi!',
    'teacher.homework.failedToCreate': 'Uy vazifasini yaratishda xatolik yuz berdi',

    // Student Panel - Dashboard
    'student.dashboard.title': 'O\'quvchi paneli',
    'student.dashboard.welcome': 'Xush kelibsiz',
    'student.dashboard.mySchedule': 'Mening jadvalim',
    'student.dashboard.upcomingLessons': 'Kutilayotgan darslar',
    'student.dashboard.attendance': 'Davomat',
    'student.dashboard.academicPerformance': 'O\'quv natijalari',
    'student.dashboard.recentGrades': 'So\'nggi baholar',
    'student.dashboard.pendingHomework': 'Kutilayotgan uy vazifalari',
    'student.dashboard.weeklyAverage': 'Haftalik o\'rtacha',
    'student.dashboard.subjectPerformance': 'Fanlar bo\'yicha natija',
    'student.dashboard.attendanceRate': 'Davomat foizi',
    'student.dashboard.grade': 'Baho',
    'student.dashboard.percentage': 'Foiz',
    'student.dashboard.level': 'Daraja',
    'student.dashboard.excellent': 'A\'lo',
    'student.dashboard.good': 'Yaxshi',
    'student.dashboard.satisfactory': 'Qoniqarli',
    'student.dashboard.needsImprovement': 'Yaxshilanish kerak',
    'student.dashboard.improving': 'Yaxshilanmoqda',
    'student.dashboard.declining': 'Pasaymoqda',
    'student.dashboard.stable': 'Barqaror',
    'student.dashboard.trend': 'Tendensiya',
    'student.schedule.completed': 'TUGAGAN',
    'student.schedule.upcoming': 'KUTILAYOTGAN',
    'student.attendance.present': 'Hozir',
    'student.attendance.absent': 'Yo\'q',
    'student.attendance.late': 'Kech kelgan',
    'student.attendance.excused': 'Uzrli',

    // Student Panel - Grades
    'student.grades.title': 'Mening baholarim',
    'student.grades.gradeOverview': 'Baho umumiy ko\'rinishi',
    'student.grades.examResults': 'Imtihon natijalari',
    'student.grades.performanceAnalytics': 'Natija tahlili',
    'student.grades.mobileView': 'Mobil ko\'rinish',
    'student.grades.currentYear': 'Joriy yil',
    'student.grades.pastYears': 'O\'tgan yillar',
    'student.grades.archivedRecords': 'Arxiv yozuvlar',
    'student.grades.overallAverage': 'Umumiy o\'rtacha',
    'student.grades.highestScore': 'Eng yuqori baho',
    'student.grades.gradeAverage': 'Baho o\'rtachasi',
    'student.grades.totalGrades': 'Jami baholar',
    'student.grades.personalBest': 'Shaxsiy rekord',
    'student.grades.subject': 'Fan',
    'student.grades.average': 'O\'rtacha',
    'student.grades.grades': 'baholar',
    'student.grades.exams': 'imtihonlar',
    'student.grades.progressChart': 'Rivojlanish grafigi',
    'student.grades.studentName': 'O\'quvchi nomi',
    'student.grades.detailedRecords': 'Batafsil yozuvlar',
    'student.grades.gradeType': 'Baho turi',
    'student.grades.byType': 'Turi bo\'yicha',
    'student.grades.recentActivity': 'So\'nggi faoliyat',
    'student.grades.performanceInsights': 'Natija tahlillari',
    'student.grades.consistentPerformance': 'Ajoyib ishlash! Siz doimo yuqori natijalarga erishmoqdasiz.',
    'student.grades.goodWork': 'Yaxshi ish! Yuqori darajaga erishish uchun harakatni davom ettiring.',
    'student.grades.steadyProgress': 'Barqaror rivojlanish. Qiyin fanlarga ko\'proq vaqt ajrating.',
    'student.grades.focusOnImprovement': 'Yaxshilanishga e\'tibor qarating. Qo\'shimcha yordam uchun o\'qituvchilarga murojaat qiling.',
    'student.grades.exportReport': 'Hisobotni eksport qilish',

    // Forms and Modals
    'form.student': 'O\'quvchi',
    'form.subject': 'Fan',
    'form.class': 'Sinf',
    'form.date': 'Sana',
    'form.time': 'Vaqt',
    'form.description': 'Tavsif',
    'form.status': 'Holat',
    'form.type': 'Turi',
    'form.title': 'Sarlavha',
    'form.name': 'Nomi',
    'form.email': 'Email',
    'form.phone': 'Telefon',
    'form.address': 'Manzil',
    'form.required': 'Majburiy',
    'form.optional': 'Ixtiyoriy',
    'form.selectOption': 'Variantni tanlang',
    'form.enterText': 'Matn kiriting',
    'form.uploadFile': 'Fayl yuklash',
    'form.remove': 'Olib tashlash',
    'form.add': 'Qoshish',
    'form.create': 'Yaratish',
    'form.update': 'Yangilash',
    'form.delete': 'O\'chirish',
    'form.confirm': 'Tasdiqlash',
    'form.yes': 'Ha',
    'form.no': 'Yo\'q',
    'form.ok': 'OK',
    'form.close': 'Yopish',
    'form.back': 'Orqaga',
    'form.next': 'Keyingi',
    'form.previous': 'Oldingi',
    'form.finish': 'Tugallash',
    'form.reset': 'Qayta tiklash',
    'form.clear': 'Tozalash',
    'form.search': 'Qidirish',
    'form.filter': 'Filtr',
    'form.sort': 'Saralash',
    'form.export': 'Eksport',
    'form.import': 'Import',
    'form.print': 'Chop etish',
    'form.share': 'Ulashish',

    // Common UI Elements
    'ui.loading': 'Yuklanmoqda...',
    'ui.noData': 'Ma\'lumotlar yo\'q',
    'ui.noResults': 'Natijalar topilmadi',
    'ui.tryAgain': 'Qayta urinib ko\'ring',
    'ui.refresh': 'Yangilash',
    'ui.retry': 'Qayta urinish',
    'ui.error': 'Xatolik yuz berdi',
    'ui.success': 'Muvaffaqiyat',
    'ui.warning': 'Ogohlantirish',
    'ui.info': 'Ma\'lumot',
    'ui.confirm': 'Tasdiqlaysizmi?',
    'ui.cancel': 'Bekor qilish',
    'ui.save': 'Saqlash',
    'ui.edit': 'Tahrirlash',
    'ui.delete': 'O\'chirish',
    'ui.view': 'Ko\'rish',
    'ui.add': 'Qoshish',
    'ui.remove': 'Olib tashlash',
    'ui.select': 'Tanlash',
    'ui.selected': 'Tanlandi',
    'ui.all': 'Hammasi',
    'ui.none': 'Hech narsa',
    'ui.today': 'Bugun',
    'ui.yesterday': 'Kecha',
    'ui.tomorrow': 'Ertaga',
    'ui.thisWeek': 'Bu hafta',
    'ui.thisMonth': 'Bu oy',
    'ui.thisYear': 'Bu yil',
    'ui.lastWeek': 'O\'tgan hafta',
    'ui.lastMonth': 'O\'tgan oy',
    'ui.lastYear': 'O\'tgan yil',
    'ui.from': 'dan',
    'ui.to': 'gacha',
    'ui.and': 'va',
    'ui.or': 'yoki',
    'ui.with': 'bilan',
    'ui.by': 'tomonidan',
    'ui.at': 'da',
    'ui.on': 'da',
    'ui.in': 'da',
    'ui.for': 'uchun',

    // Language selector
    'language.uzbek': 'O\'zbek',
    'language.russian': 'Русский',
    'language.english': 'English',
    'language.select': 'Tilni tanlang',
  },
  ru: {
    // Navigation
    'nav.dashboard': 'Панель управления',
    'nav.attendance': 'Посещаемость',
    'nav.homework': 'Домашнее задание',
    'nav.gradebook': 'Журнал оценок',
    'nav.profile': 'Профиль',
    'nav.settings': 'Настройки',
    'nav.logout': 'Выйти',
    'nav.search': 'Поиск...',
    
    // Teacher specific
    'teacher.myStudents': 'Мои ученики',
    'teacher.myClasses': 'Мои классы',
    'teacher.exams': 'Экзамены',
    'teacher.announcements': 'Объявления',
    
    // Student specific
    'student.myGrades': 'Мои оценки',
    'student.exams': 'Экзамены',
    'student.results': 'Результаты',
    'student.announcements': 'Объявления',
    
    // Common
    'common.homework': 'Домашнее задание',
    'common.attendance': 'Посещаемость',
    'common.grades': 'Оценки',
    'common.submit': 'Отправить',
    'common.cancel': 'Отмена',
    'common.save': 'Сохранить',
    'common.edit': 'Редактировать',
    'common.delete': 'Удалить',
    'common.view': 'Просмотр',
    'common.download': 'Скачать',
    'common.upload': 'Загрузить',
    'common.filter': 'Фильтр',
    'common.search': 'Поиск',
    'common.loading': 'Загрузка...',
    'common.error': 'Ошибка',
    'common.success': 'Успех',
    'common.warning': 'Предупреждение',
    'common.info': 'Информация',
    
    // Homework
    'homework.title': 'Домашнее задание',
    'homework.dueDate': 'Срок сдачи',
    'homework.subject': 'Предмет',
    'homework.description': 'Описание',
    'homework.status': 'Статус',
    'homework.submitted': 'Сдано',
    'homework.pending': 'Ожидает',
    'homework.graded': 'Оценено',
    'homework.overdue': 'Просрочено',
    'homework.submit': 'Сдать',
    'homework.update': 'Обновить',
    'homework.view': 'Просмотр',
    'homework.grade': 'Оценка',
    'homework.feedback': 'Отзыв',
    'homework.attachments': 'Вложения',
    'homework.textContent': 'Текстовое содержание',
    'homework.voiceRecording': 'Голосовая запись',
    'homework.uploadFile': 'Загрузить файл',
    'homework.recordVoice': 'Записать голос',
    'homework.removeContent': 'Удалить содержание',
    'homework.removeAttachment': 'Удалить вложение',
    'homework.submissionDetails': 'Детали сдачи',
    'homework.teacherFeedback': 'Отзыв учителя',
    'homework.submittedAt': 'Сдано в',
    'homework.gradedAt': 'Оценено в',
    
    // Attendance
    'attendance.title': 'Посещаемость',
    'attendance.present': 'Присутствует',
    'attendance.absent': 'Отсутствует',
    'attendance.late': 'Опоздал',
    'attendance.excused': 'Уважительная причина',
    'attendance.analytics': 'Аналитика',
    'attendance.tracker': '30-дневный трекер',
    'attendance.statistics': 'Статистика',
    'attendance.percentage': 'Процент',
    'attendance.period': 'Период',
    'attendance.last7days': 'Последние 7 дней',
    'attendance.last4weeks': 'Последние 4 недели',
    'attendance.last12weeks': 'Последние 12 недель',
    'attendance.thisYear': 'Этот год',
    'attendance.filter': 'Фильтр',
    'attendance.allSubjects': 'Все предметы',
    'attendance.month': 'Месяц',
    'attendance.previousMonth': 'Предыдущий месяц',
    'attendance.nextMonth': 'Следующий месяц',
    'attendance.takeAttendance': 'Отметить посещаемость',
    'attendance.loading': 'Загрузка...',
    'attendance.noStudents': 'Студенты не найдены',
    'attendance.quickActions': 'Быстрые действия',
    'attendance.markAllPresent': 'Отметить всех присутствующими',
    'attendance.markAllAbsent': 'Отметить всех отсутствующими',
    'attendance.markAllLate': 'Отметить всех опоздавшими',
    'attendance.markAllExcused': 'Отметить всех по уважительной причине',
    'attendance.addNotes': 'Добавить заметки (необязательно)',
    'attendance.saveAttendance': 'Сохранить посещаемость',
    'attendance.saving': 'Сохранение...',
    'attendance.saved': 'Посещаемость успешно сохранена!',
    'attendance.failedToSave': 'Ошибка при сохранении посещаемости',
    'attendance.cancel': 'Отмена',
    
    // Teacher Panel - Schedule Dashboard
    'teacher.schedule.title': 'Расписание уроков',
    'teacher.schedule.lesson': 'Урок',
    'teacher.schedule.room': 'Кабинет',
    'teacher.schedule.class': 'Класс',
    'teacher.schedule.subject': 'Предмет',
    'teacher.schedule.time': 'Время',
    'teacher.schedule.topic': 'Тема',
    'teacher.schedule.takeAttendance': 'Отметить посещаемость',
    'teacher.schedule.inputGrades': 'Ввести оценки',
    'teacher.schedule.assignHomework': 'Задать домашнее задание',
    'teacher.schedule.editTopic': 'Редактировать тему',
    'teacher.schedule.upcoming': 'Предстоящие',
    'teacher.schedule.inProgress': 'Идет урок',
    'teacher.schedule.completed': 'Завершен',
    'teacher.schedule.noLessons': 'Сегодня уроков нет',
    'teacher.schedule.enjoyFreeTime': 'Наслаждайтесь свободным временем!',
    'teacher.schedule.quickActions': 'Быстрые действия',
    'teacher.schedule.markAllPresent': 'Отметить всех присутствующими',
    'teacher.schedule.markAllAbsent': 'Отметить всех отсутствующими',
    'teacher.schedule.markAllLate': 'Отметить всех опоздавшими',
    'teacher.schedule.markAllExcused': 'Отметить всех по уважительной причине',
    'teacher.schedule.addNotes': 'Добавить заметки (необязательно)',
    'teacher.schedule.saveAttendance': 'Сохранить посещаемость',
    'teacher.schedule.attendanceSaved': 'Посещаемость успешно сохранена!',
    'teacher.schedule.failedToSave': 'Ошибка при сохранении посещаемости',
    'teacher.schedule.subjectTeacher': 'Учитель предмета',
    'teacher.schedule.supervisor': 'Руководитель',
    'teacher.schedule.attendanceUpcoming': 'Посещаемость доступна при начале урока',
    'teacher.schedule.attendanceCompleted': 'Урок завершен - посещаемость закрыта',
    'teacher.schedule.attendanceAvailable': 'Отметить посещаемость',
    'teacher.schedule.status.upcoming': 'Предстоящие',
    'teacher.schedule.status.inProgress': 'Идет урок',
    'teacher.schedule.status.completed': 'Завершен',

    // Teacher Panel - Grades
    'teacher.grades.title': 'Оценки',
    'teacher.grades.inputGrades': 'Ввод оценок',
    'teacher.grades.gradeTracker': 'Отслеживание оценок',
    'teacher.grades.analytics': 'Аналитика',
    'teacher.grades.assignmentTitle': 'Название задания',
    'teacher.grades.maxScore': 'Максимальный балл',
    'teacher.grades.gradeType': 'Тип оценки',
    'teacher.grades.dailyGrade': 'Ежедневная оценка',
    'teacher.grades.homework': 'Домашнее задание',
    'teacher.grades.quiz': 'Тест',
    'teacher.grades.test': 'Экзамен',
    'teacher.grades.project': 'Проект',
    'teacher.grades.participation': 'Участие',
    'teacher.grades.excellent': 'Отлично (90-100%)',
    'teacher.grades.good': 'Хорошо (80-89%)',
    'teacher.grades.satisfactory': 'Удовлетворительно (70-79%)',
    'teacher.grades.needsImprovement': 'Нуждается в улучшении (0-69%)',
    'teacher.grades.outOf': 'из',
    'teacher.grades.feedback': 'Обратная связь',
    'teacher.grades.saveGrades': 'Сохранить оценки',
    'teacher.grades.gradesSaved': 'Оценки успешно сохранены!',
    'teacher.grades.failedToSave': 'Ошибка при сохранении оценок',
    'teacher.grades.student': 'Студент',
    'teacher.grades.score': 'Балл',
    'teacher.grades.grade': 'Оценка',
    'teacher.grades.percentage': 'Процент',
    'teacher.grades.letterGrade': 'Буквенная оценка',
    'teacher.grades.date': 'Дата',
    'teacher.grades.type': 'Тип',

    // Teacher Panel - Homework
    'teacher.homework.title': 'Домашнее задание',
    'teacher.homework.create': 'Создать домашнее задание',
    'teacher.homework.assign': 'Назначить домашнее задание',
    'teacher.homework.titleField': 'Заголовок',
    'teacher.homework.description': 'Описание',
    'teacher.homework.instructions': 'Инструкции',
    'teacher.homework.dueDate': 'Срок сдачи',
    'teacher.homework.totalPoints': 'Общее количество баллов',
    'teacher.homework.passingPoints': 'Проходные баллы',
    'teacher.homework.allowLate': 'Разрешить позднюю сдачу',
    'teacher.homework.latePenalty': 'Штраф за позднюю сдачу',
    'teacher.homework.attachments': 'Вложения',
    'teacher.homework.uploadFiles': 'Загрузить файлы',
    'teacher.homework.fileSelected': 'файл выбран',
    'teacher.homework.filesSelected': 'файлов выбрано',
    'teacher.homework.removeFile': 'Удалить файл',
    'teacher.homework.createHomework': 'Создать домашнее задание',
    'teacher.homework.homeworkCreated': 'Домашнее задание успешно создано!',
    'teacher.homework.failedToCreate': 'Ошибка при создании домашнего задания',

    // Student Panel - Dashboard
    'student.dashboard.title': 'Панель студента',
    'student.dashboard.welcome': 'Добро пожаловать',
    'student.dashboard.mySchedule': 'Мое расписание',
    'student.dashboard.upcomingLessons': 'Предстоящие уроки',
    'student.dashboard.attendance': 'Посещаемость',
    'student.dashboard.academicPerformance': 'Академическая успеваемость',
    'student.dashboard.recentGrades': 'Последние оценки',
    'student.dashboard.pendingHomework': 'Ожидающие домашние задания',
    'student.dashboard.weeklyAverage': 'Средний за неделю',
    'student.dashboard.subjectPerformance': 'Успеваемость по предметам',
    'student.dashboard.attendanceRate': 'Процент посещаемости',
    'student.dashboard.grade': 'Оценка',
    'student.dashboard.percentage': 'Процент',
    'student.dashboard.level': 'Уровень',
    'student.dashboard.excellent': 'Отлично',
    'student.dashboard.good': 'Хорошо',
    'student.dashboard.satisfactory': 'Удовлетворительно',
    'student.dashboard.needsImprovement': 'Нуждается в улучшении',
    'student.dashboard.improving': 'Улучшается',
    'student.dashboard.declining': 'Снижается',
    'student.dashboard.stable': 'Стабильно',
    'student.dashboard.trend': 'Тенденция',
    'student.schedule.completed': 'ЗАВЕРШЕН',
    'student.schedule.upcoming': 'ПРЕДСТОЯЩИЙ',
    'student.attendance.present': 'Присутствует',
    'student.attendance.absent': 'Отсутствует',
    'student.attendance.late': 'Опоздал',
    'student.attendance.excused': 'Уважительная причина',

    // Student Panel - Grades
    'student.grades.title': 'Мои оценки',
    'student.grades.gradeOverview': 'Обзор оценок',
    'student.grades.examResults': 'Результаты экзаменов',
    'student.grades.performanceAnalytics': 'Аналитика успеваемости',
    'student.grades.mobileView': 'Мобильный вид',
    'student.grades.currentYear': 'Текущий год',
    'student.grades.pastYears': 'Прошлые годы',
    'student.grades.archivedRecords': 'Архивные записи',
    'student.grades.overallAverage': 'Общий средний',
    'student.grades.highestScore': 'Высший балл',
    'student.grades.gradeAverage': 'Средняя оценка',
    'student.grades.totalGrades': 'Всего оценок',
    'student.grades.personalBest': 'Личный рекорд',
    'student.grades.subject': 'Предмет',
    'student.grades.average': 'Средний',
    'student.grades.grades': 'оценок',
    'student.grades.exams': 'экзаменов',
    'student.grades.progressChart': 'График прогресса',
    'student.grades.studentName': 'Имя студента',
    'student.grades.detailedRecords': 'Подробные записи',
    'student.grades.gradeType': 'Тип оценки',
    'student.grades.byType': 'По типу',
    'student.grades.recentActivity': 'Недавняя активность',
    'student.grades.performanceInsights': 'Аналитика успеваемости',
    'student.grades.consistentPerformance': 'Отличная работа! Вы постоянно достигаете высоких результатов.',
    'student.grades.goodWork': 'Хорошая работа! Продолжайте в том же духе, чтобы достичь совершенства.',
    'student.grades.steadyProgress': 'Стабильный прогресс. Уделите больше времени сложным предметам.',
    'student.grades.focusOnImprovement': 'Сосредоточьтесь на улучшении. Обратитесь к учителям за дополнительной помощью.',
    'student.grades.exportReport': 'Экспортировать отчет',

    // Forms and Modals
    'form.student': 'Студент',
    'form.subject': 'Предмет',
    'form.class': 'Класс',
    'form.date': 'Дата',
    'form.time': 'Время',
    'form.description': 'Описание',
    'form.status': 'Статус',
    'form.type': 'Тип',
    'form.title': 'Заголовок',
    'form.name': 'Имя',
    'form.email': 'Email',
    'form.phone': 'Телефон',
    'form.address': 'Адрес',
    'form.required': 'Обязательно',
    'form.optional': 'Необязательно',
    'form.selectOption': 'Выберите вариант',
    'form.enterText': 'Введите текст',
    'form.uploadFile': 'Загрузить файл',
    'form.remove': 'Удалить',
    'form.add': 'Добавить',
    'form.create': 'Создать',
    'form.update': 'Обновить',
    'form.delete': 'Удалить',
    'form.confirm': 'Подтвердить',
    'form.yes': 'Да',
    'form.no': 'Нет',
    'form.ok': 'OK',
    'form.close': 'Закрыть',
    'form.back': 'Назад',
    'form.next': 'Далее',
    'form.previous': 'Предыдущий',
    'form.finish': 'Завершить',
    'form.reset': 'Сбросить',
    'form.clear': 'Очистить',
    'form.search': 'Поиск',
    'form.filter': 'Фильтр',
    'form.sort': 'Сортировка',
    'form.export': 'Экспорт',
    'form.import': 'Импорт',
    'form.print': 'Печать',
    'form.share': 'Поделиться',

    // Common UI Elements
    'ui.loading': 'Загрузка...',
    'ui.noData': 'Нет данных',
    'ui.noResults': 'Результаты не найдены',
    'ui.tryAgain': 'Попробуйте еще раз',
    'ui.refresh': 'Обновить',
    'ui.retry': 'Повторить',
    'ui.error': 'Произошла ошибка',
    'ui.success': 'Успех',
    'ui.warning': 'Предупреждение',
    'ui.info': 'Информация',
    'ui.confirm': 'Подтверждаете?',
    'ui.cancel': 'Отмена',
    'ui.save': 'Сохранить',
    'ui.edit': 'Редактировать',
    'ui.delete': 'Удалить',
    'ui.view': 'Просмотр',
    'ui.add': 'Добавить',
    'ui.remove': 'Удалить',
    'ui.select': 'Выбрать',
    'ui.selected': 'Выбрано',
    'ui.all': 'Все',
    'ui.none': 'Ничего',
    'ui.today': 'Сегодня',
    'ui.yesterday': 'Вчера',
    'ui.tomorrow': 'Завтра',
    'ui.thisWeek': 'Эта неделя',
    'ui.thisMonth': 'Этот месяц',
    'ui.thisYear': 'Этот год',
    'ui.lastWeek': 'Прошлая неделя',
    'ui.lastMonth': 'Прошлый месяц',
    'ui.lastYear': 'Прошлый год',
    'ui.from': 'от',
    'ui.to': 'до',
    'ui.and': 'и',
    'ui.or': 'или',
    'ui.with': 'с',
    'ui.by': 'от',
    'ui.at': 'в',
    'ui.on': 'на',
    'ui.in': 'в',
    'ui.for': 'для',

    // Language selector
    'language.uzbek': 'O\'zbek',
    'language.russian': 'Русский',
    'language.english': 'English',
    'language.select': 'Выберите язык',
  },
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.attendance': 'Attendance',
    'nav.homework': 'Homework',
    'nav.gradebook': 'Gradebook',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    'nav.search': 'Search...',
    
    // Teacher specific
    'teacher.myStudents': 'My Students',
    'teacher.myClasses': 'My Classes',
    'teacher.exams': 'Exams',
    'teacher.announcements': 'Announcements',
    
    // Student specific
    'student.myGrades': 'My Grades',
    'student.exams': 'Exams',
    'student.results': 'Results',
    'student.announcements': 'Announcements',
    
    // Common
    'common.homework': 'Homework',
    'common.attendance': 'Attendance',
    'common.grades': 'Grades',
    'common.submit': 'Submit',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view': 'View',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.filter': 'Filter',
    'common.search': 'Search',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Info',
    
    // Homework
    'homework.title': 'Homework',
    'homework.dueDate': 'Due Date',
    'homework.subject': 'Subject',
    'homework.description': 'Description',
    'homework.status': 'Status',
    'homework.submitted': 'Submitted',
    'homework.pending': 'Pending',
    'homework.graded': 'Graded',
    'homework.overdue': 'Overdue',
    'homework.submit': 'Submit',
    'homework.update': 'Update',
    'homework.view': 'View',
    'homework.grade': 'Grade',
    'homework.feedback': 'Feedback',
    'homework.attachments': 'Attachments',
    'homework.textContent': 'Text Content',
    'homework.voiceRecording': 'Voice Recording',
    'homework.uploadFile': 'Upload File',
    'homework.recordVoice': 'Record Voice',
    'homework.removeContent': 'Remove Content',
    'homework.removeAttachment': 'Remove Attachment',
    'homework.submissionDetails': 'Submission Details',
    'homework.teacherFeedback': 'Teacher Feedback',
    'homework.submittedAt': 'Submitted At',
    'homework.gradedAt': 'Graded At',
    
    // Attendance
    'attendance.title': 'Attendance',
    'attendance.present': 'Present',
    'attendance.absent': 'Absent',
    'attendance.late': 'Late',
    'attendance.excused': 'Excused',
    'attendance.analytics': 'Analytics',
    'attendance.tracker': '30-Day Tracker',
    'attendance.statistics': 'Statistics',
    'attendance.percentage': 'Percentage',
    'attendance.period': 'Period',
    'attendance.last7days': 'Last 7 Days',
    'attendance.last4weeks': 'Last 4 Weeks',
    'attendance.last12weeks': 'Last 12 Weeks',
    'attendance.thisYear': 'This Year',
    'attendance.filter': 'Filter',
    'attendance.allSubjects': 'All Subjects',
    'attendance.month': 'Month',
    'attendance.previousMonth': 'Previous Month',
    'attendance.nextMonth': 'Next Month',
    'attendance.takeAttendance': 'Take Attendance',
    'attendance.loading': 'Loading...',
    'attendance.noStudents': 'No students found',
    'attendance.quickActions': 'Quick Actions',
    'attendance.markAllPresent': 'Mark All Present',
    'attendance.markAllAbsent': 'Mark All Absent',
    'attendance.markAllLate': 'Mark All Late',
    'attendance.markAllExcused': 'Mark All Excused',
    'attendance.addNotes': 'Add notes (optional)',
    'attendance.saveAttendance': 'Save Attendance',
    'attendance.saving': 'Saving...',
    'attendance.saved': 'Attendance saved successfully!',
    'attendance.failedToSave': 'Failed to save attendance',
    'attendance.cancel': 'Cancel',
    
    // Teacher Panel - Schedule Dashboard
    'teacher.schedule.title': 'Lesson Schedule',
    'teacher.schedule.lesson': 'Lesson',
    'teacher.schedule.room': 'Room',
    'teacher.schedule.class': 'Class',
    'teacher.schedule.subject': 'Subject',
    'teacher.schedule.time': 'Time',
    'teacher.schedule.topic': 'Topic',
    'teacher.schedule.takeAttendance': 'Take Attendance',
    'teacher.schedule.inputGrades': 'Input Grades',
    'teacher.schedule.assignHomework': 'Assign Homework',
    'teacher.schedule.editTopic': 'Edit Topic',
    'teacher.schedule.upcoming': 'Upcoming',
    'teacher.schedule.inProgress': 'In Progress',
    'teacher.schedule.completed': 'Completed',
    'teacher.schedule.noLessons': 'No lessons today',
    'teacher.schedule.enjoyFreeTime': 'Enjoy your free time!',
    'teacher.schedule.quickActions': 'Quick Actions',
    'teacher.schedule.markAllPresent': 'Mark All Present',
    'teacher.schedule.markAllAbsent': 'Mark All Absent',
    'teacher.schedule.markAllLate': 'Mark All Late',
    'teacher.schedule.markAllExcused': 'Mark All Excused',
    'teacher.schedule.addNotes': 'Add notes (optional)',
    'teacher.schedule.saveAttendance': 'Save Attendance',
    'teacher.schedule.attendanceSaved': 'Attendance saved successfully!',
    'teacher.schedule.failedToSave': 'Failed to save attendance',
    'teacher.schedule.subjectTeacher': 'Subject Teacher',
    'teacher.schedule.supervisor': 'Supervisor',
    'teacher.schedule.noLessonTopic': 'No lesson topic',
    'teacher.schedule.attendanceUpcoming': 'Attendance available when lesson starts',
    'teacher.schedule.attendanceCompleted': 'Lesson completed - attendance closed',
    'teacher.schedule.attendanceAvailable': 'Take Attendance',
    'teacher.schedule.status.upcoming': 'Upcoming',
    'teacher.schedule.status.inProgress': 'In Progress',
    'teacher.schedule.status.completed': 'Completed',

    // Teacher Panel - Grades
    'teacher.grades.title': 'Grades',
    'teacher.grades.inputGrades': 'Input Grades',
    'teacher.grades.gradeTracker': 'Grade Tracker',
    'teacher.grades.analytics': 'Analytics',
    'teacher.grades.assignmentTitle': 'Assignment Title',
    'teacher.grades.maxScore': 'Maximum Score',
    'teacher.grades.gradeType': 'Grade Type',
    'teacher.grades.dailyGrade': 'Daily Grade',
    'teacher.grades.homework': 'Homework',
    'teacher.grades.quiz': 'Quiz',
    'teacher.grades.test': 'Test',
    'teacher.grades.project': 'Project',
    'teacher.grades.participation': 'Participation',
    'teacher.grades.excellent': 'Excellent (90-100%)',
    'teacher.grades.good': 'Good (80-89%)',
    'teacher.grades.satisfactory': 'Satisfactory (70-79%)',
    'teacher.grades.needsImprovement': 'Needs Improvement (0-69%)',
    'teacher.grades.outOf': 'out of',
    'teacher.grades.feedback': 'Feedback',
    'teacher.grades.saveGrades': 'Save Grades',
    'teacher.grades.gradesSaved': 'Grades saved successfully!',
    'teacher.grades.failedToSave': 'Failed to save grades',
    'teacher.grades.student': 'Student',
    'teacher.grades.score': 'Score',
    'teacher.grades.grade': 'Grade',
    'teacher.grades.percentage': 'Percentage',
    'teacher.grades.letterGrade': 'Letter Grade',
    'teacher.grades.date': 'Date',
    'teacher.grades.type': 'Type',

    // Teacher Panel - Homework
    'teacher.homework.title': 'Homework',
    'teacher.homework.create': 'Create Homework',
    'teacher.homework.assign': 'Assign Homework',
    'teacher.homework.titleField': 'Title',
    'teacher.homework.description': 'Description',
    'teacher.homework.instructions': 'Instructions',
    'teacher.homework.dueDate': 'Due Date',
    'teacher.homework.totalPoints': 'Total Points',
    'teacher.homework.passingPoints': 'Passing Points',
    'teacher.homework.allowLate': 'Allow Late Submission',
    'teacher.homework.latePenalty': 'Late Penalty',
    'teacher.homework.attachments': 'Attachments',
    'teacher.homework.uploadFiles': 'Upload Files',
    'teacher.homework.fileSelected': 'file selected',
    'teacher.homework.filesSelected': 'files selected',
    'teacher.homework.removeFile': 'Remove File',
    'teacher.homework.createHomework': 'Create Homework',
    'teacher.homework.homeworkCreated': 'Homework created successfully!',
    'teacher.homework.failedToCreate': 'Failed to create homework',

    // Student Panel - Dashboard
    'student.dashboard.title': 'Student Dashboard',
    'student.dashboard.welcome': 'Welcome',
    'student.dashboard.mySchedule': 'My Schedule',
    'student.dashboard.upcomingLessons': 'Upcoming Lessons',
    'student.dashboard.attendance': 'Attendance',
    'student.dashboard.academicPerformance': 'Academic Performance',
    'student.dashboard.recentGrades': 'Recent Grades',
    'student.dashboard.pendingHomework': 'Pending Homework',
    'student.dashboard.weeklyAverage': 'Weekly Average',
    'student.dashboard.subjectPerformance': 'Subject Performance',
    'student.dashboard.attendanceRate': 'Attendance Rate',
    'student.dashboard.grade': 'Grade',
    'student.dashboard.percentage': 'Percentage',
    'student.dashboard.level': 'Level',
    'student.dashboard.excellent': 'Excellent',
    'student.dashboard.good': 'Good',
    'student.dashboard.satisfactory': 'Satisfactory',
    'student.dashboard.needsImprovement': 'Needs Improvement',
    'student.dashboard.improving': 'Improving',
    'student.dashboard.declining': 'Declining',
    'student.dashboard.stable': 'Stable',
    'student.dashboard.trend': 'Trend',
    'student.schedule.completed': 'COMPLETED',
    'student.schedule.upcoming': 'UPCOMING',
    'student.attendance.present': 'Present',
    'student.attendance.absent': 'Absent',
    'student.attendance.late': 'Late',
    'student.attendance.excused': 'Excused',

    // Student Panel - Grades
    'student.grades.title': 'My Grades',
    'student.grades.gradeOverview': 'Grade Overview',
    'student.grades.examResults': 'Exam Results',
    'student.grades.performanceAnalytics': 'Performance Analytics',
    'student.grades.mobileView': 'Mobile View',
    'student.grades.currentYear': 'Current Year',
    'student.grades.pastYears': 'Past Years',
    'student.grades.archivedRecords': 'Archived Records',
    'student.grades.overallAverage': 'Overall Average',
    'student.grades.highestScore': 'Highest Score',
    'student.grades.gradeAverage': 'Grade Average',
    'student.grades.totalGrades': 'Total Grades',
    'student.grades.personalBest': 'Personal Best',
    'student.grades.subject': 'Subject',
    'student.grades.average': 'Average',
    'student.grades.grades': 'grades',
    'student.grades.exams': 'exams',
    'student.grades.progressChart': 'Progress Chart',
    'student.grades.studentName': 'Student Name',
    'student.grades.detailedRecords': 'Detailed Records',
    'student.grades.gradeType': 'Grade Type',
    'student.grades.byType': 'By Type',
    'student.grades.recentActivity': 'Recent Activity',
    'student.grades.performanceInsights': 'Performance Insights',
    'student.grades.consistentPerformance': 'Excellent performance! You consistently achieve high results.',
    'student.grades.goodWork': 'Good work! Keep up the momentum to reach excellence.',
    'student.grades.steadyProgress': 'Steady progress. Consider spending more time on challenging subjects.',
    'student.grades.focusOnImprovement': 'Focus on improvement. Talk to your teachers for additional support.',
    'student.grades.exportReport': 'Export Report',

    // Forms and Modals
    'form.student': 'Student',
    'form.subject': 'Subject',
    'form.class': 'Class',
    'form.date': 'Date',
    'form.time': 'Time',
    'form.description': 'Description',
    'form.status': 'Status',
    'form.type': 'Type',
    'form.title': 'Title',
    'form.name': 'Name',
    'form.email': 'Email',
    'form.phone': 'Phone',
    'form.address': 'Address',
    'form.required': 'Required',
    'form.optional': 'Optional',
    'form.selectOption': 'Select an option',
    'form.enterText': 'Enter text',
    'form.uploadFile': 'Upload File',
    'form.remove': 'Remove',
    'form.add': 'Add',
    'form.create': 'Create',
    'form.update': 'Update',
    'form.delete': 'Delete',
    'form.confirm': 'Confirm',
    'form.yes': 'Yes',
    'form.no': 'No',
    'form.ok': 'OK',
    'form.close': 'Close',
    'form.back': 'Back',
    'form.next': 'Next',
    'form.previous': 'Previous',
    'form.finish': 'Finish',
    'form.reset': 'Reset',
    'form.clear': 'Clear',
    'form.search': 'Search',
    'form.filter': 'Filter',
    'form.sort': 'Sort',
    'form.export': 'Export',
    'form.import': 'Import',
    'form.print': 'Print',
    'form.share': 'Share',

    // Common UI Elements
    'ui.loading': 'Loading...',
    'ui.noData': 'No data available',
    'ui.noResults': 'No results found',
    'ui.tryAgain': 'Try again',
    'ui.refresh': 'Refresh',
    'ui.retry': 'Retry',
    'ui.error': 'An error occurred',
    'ui.success': 'Success',
    'ui.warning': 'Warning',
    'ui.info': 'Information',
    'ui.confirm': 'Are you sure?',
    'ui.cancel': 'Cancel',
    'ui.save': 'Save',
    'ui.edit': 'Edit',
    'ui.delete': 'Delete',
    'ui.view': 'View',
    'ui.add': 'Add',
    'ui.remove': 'Remove',
    'ui.select': 'Select',
    'ui.selected': 'Selected',
    'ui.all': 'All',
    'ui.none': 'None',
    'ui.today': 'Today',
    'ui.yesterday': 'Yesterday',
    'ui.tomorrow': 'Tomorrow',
    'ui.thisWeek': 'This Week',
    'ui.thisMonth': 'This Month',
    'ui.thisYear': 'This Year',
    'ui.lastWeek': 'Last Week',
    'ui.lastMonth': 'Last Month',
    'ui.lastYear': 'Last Year',
    'ui.from': 'from',
    'ui.to': 'to',
    'ui.and': 'and',
    'ui.or': 'or',
    'ui.with': 'with',
    'ui.by': 'by',
    'ui.at': 'at',
    'ui.on': 'on',
    'ui.in': 'in',
    'ui.for': 'for',

    // Language selector
    'language.uzbek': 'O\'zbek',
    'language.russian': 'Русский',
    'language.english': 'English',
    'language.select': 'Select Language',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('selectedLanguage') as Language;
    if (savedLanguage && ['uz', 'ru', 'en'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  // Save language to localStorage when it changes
  useEffect(() => {
    localStorage.setItem('selectedLanguage', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
